version: '2'
services:
    cervejanet-app:
        image: cervejanet
        external_links:
            - cervejanet-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cervejanet?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    cervejanet-mysql:
        extends:
            file: mysql.yml
            service: cervejanet-mysql
